### ISSUE TITLE
Example fails in last `cabal run test` step

### ISSUE THREAD

**Issue by haroldcarr** [yvan-sraka/cargo-cabal#3]
I do not understand why this fails.
I have other projects on my machine that use `cabal.project` to point to dependencies on my local disk.

```
> cabal run test
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: test-0.1.0.0 (user goal)
[__1] unknown package: greetings (dependency of test)
[__1] fail (backjumping, conflict set: greetings, test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: test, greetings

> uname -a
Darwin o2020 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64 i386 Darwin

> cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library

> ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2

> cargo-cabal --version
Error: Fail to read content of `Cargo.toml` file
n.b. you have to run the command from the root folder of your Rust project

> cargo-cabal --help
Error: Fail to read content of `Cargo.toml` file
n.b. you have to run the command from the root folder of your Rust project
```

**Comment by yvan-sraka** [comment]
Hi Harold,

Thank you so much for your bug report!

It actually helps me to solve 3 different issues:

- `nix build` was broken and so the GitHub Actions CI. I fix the [`flake.nix`](https://github.com/yvan-sraka/cargo-cabal/pull/4/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0) and rewrite the test suite with a new [`tests/simple.sh`](https://github.com/yvan-sraka/cargo-cabal/pull/4/files#diff-0e7bdeb35c0f57e1bad6d54c3cf049bc59ae3e797223ec2258e6d9b302431427) scenario to reproduce the workflow described in the `README.md` ;

- I reproduced, thanks to the test, the bug you described, and discover that the `name` section of `.cabal` file [was wrongly generated](https://github.com/yvan-sraka/cargo-cabal/pull/4/files#diff-23c6c1d3e74083676bf874d7714a82c7706920574c9bb26d5d24ea0e2e2b0a4e).

- I never noticed before that `--version` and `--help` commands were broken outside a Rust project folder, [fixed it too](https://github.com/yvan-sraka/cargo-cabal/pull/4/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fc)!

Thanks again for giving a try to the project and taking the time to fill this issue :)

/Yvan

**Comment by haroldcarr** [comment]
It works for me now.   Thanks!
Soon I will give it a try in the "real" Rust codebase I want to use from Haskell.
